name: CICD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  complie:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      run: mvn compile
